"""PlannerState TypedDict definition for the LangGraph code agent.

This module defines the state shape used across the planner/solver graph.
All nodes in the graph operate on this shared state.

Ownership
=========
This module is owned by the ``langgraph_code_agent`` package. The state
definition must remain stable — any new fields require a corresponding
update to the graph node logic in ``planner.py`` and ``solver.py``.
"""

from typing import List, Optional

from typing_extensions import TypedDict


class PlannerState(TypedDict):
    """State maintained across nodes in the LangGraph execution.

    Fields
    ------
    original_task: the user-facing task prompt.
    context: optional background / environment context.
    plan: list of step descriptions generated by the planner.
    current_step_index: which plan step to execute next (0-indexed).
    step_summaries: per-step one-line summaries returned by the solver.
    created_files: unique file paths created across all steps.
    step_outputs: raw solver output for each step (for judge evaluation).
    is_complete: signals that the graph should terminate.
    final_result: concatenated result string returned to the caller.
    """

    original_task: str
    context: Optional[str]
    plan: List[str]
    current_step_index: int
    step_summaries: List[str]
    created_files: List[str]
    step_outputs: List[str]
    is_complete: bool
    final_result: Optional[str]
